apiVersion: apps/v1
kind: Deployment
metadata:
  name: keoris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keoris
  template:
    metadata:
      labels:
        app: keoris
    spec:
      containers:
      - image: okteto.dev/keoris:latest
        name: keoris
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/Lai-Monkey/HTML-ALL/raw/main/6.21_AOS_slick-master.zip"
        - name: Vless_UUID
          value: "ffa13eea-0d60-4339-a387-d364eae22215"
        - name: Vless_Path
          value: "/ffa13eea-0d60-4339-a387-d364eae22215-vless"
        - name: Vmess_UUID
          value: "ffa13eea-0d60-4339-a387-d364eae22215"
        - name: Vmess_Path
          value: "/ffa13eea-0d60-4339-a387-d364eae22215-vmess"
        - name: Share_Path
          value: "/vrnk"
